//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Skills { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string imagePath { get; set; }
        public string Role { get; set; }

        public HttpPostedFileBase UserImage { get; set; }
        public virtual tbl_skills tbl_skills { get; set; }
    }
}
